In [25]:
import numpy as np
from scipy.stats import binom
import math

p = 0.1
q = 0.9
n = 1000

mean = n*p
stdev = np.sqrt(q*mean)

print('The confidence interval is:', mean-2*stdev, mean+2*stdev)
print('The % is:', (1.96*stdev)/n)

The confidence interval is: 81.02633403898972 118.97366596101028
The % is: 0.018594192641790068


In [35]:
sample_sizes = [1000,750,500,250,100]
percentages = np.linspace(0.1,0.9,9)
matrix = np.zeros([9, 5])

for x in range(np.shape(matrix)[0]):
    for y in range(np.shape(matrix)[1]):
        p = percentages[x]
        q = 1-p
        n = sample_sizes[y]
        mean = n*p
        stdev = np.sqrt(q*mean)
        matrix[x,y] = round((2*stdev)/n, 2)*100
        
print(matrix)

[[ 2.  2.  3.  4.  6.]
 [ 3.  3.  4.  5.  8.]
 [ 3.  3.  4.  6.  9.]
 [ 3.  4.  4.  6. 10.]
 [ 3.  4.  4.  6. 10.]
 [ 3.  4.  4.  6. 10.]
 [ 3.  3.  4.  6.  9.]
 [ 3.  3.  4.  5.  8.]
 [ 2.  2.  3.  4.  6.]]
